[server]
address = ":5354"
domain = "dns.toys"


[timezones]
enabled = true

# Path to the geo location file from geonames.org
# Directory: http://download.geonames.org/export/dump/
geo_filepath = "cities15000.txt"


[fx]
enabled = false

# Frequency to refresh the currency conversion data from the API.
refresh_interval = "6h"

snapshot_enabled = true
snapshot_file = "fx.snapshot"


[myip]
enabled = true


[weather]
enabled = true

# Min time between each forecast entry in hours. Min is 30 minutes.
forecast_interval = "2h"

# Max forecasts to store.
max_entries = 5

cache_ttl = "2h"

# Useragent for the yr.no API
useragent = "github.com/knadh/dns.toys"

snapshot_enabled = true
snapshot_file = "weather.snapshot"


[units]
enabled = true
