[server]
address = ":5354"
domain = "dns.toys"


[timezones]
enabled = true

# You will need to manually download the cities file and move it into this directory
# Go to http://download.geonames.org/export/dump/ and download the cities15000.zip file
# Unzip the file and move the cities15000.txt file to the root of this directory 
geo_filepath = "cities15000.txt"

[fx]
enabled = false

# Frequency to refresh the currency conversion data from the API.
refresh_interval = "6h"

snapshot_enabled = true
snapshot_file = "fx.snapshot"


[ip]
enabled = true


[weather]
enabled = true

# Min time between each forecast entry in hours. Min is 30 minutes.
forecast_interval = "2h"

# Max forecasts to store.
max_entries = 5

cache_ttl = "2h"

# Useragent for the yr.no API
useragent = "github.com/knadh/dns.toys"

snapshot_enabled = true
snapshot_file = "weather.snapshot"


[units]
enabled = true

[num2words]
enabled = true

[cidr]
enabled = true

[pi]
enabled = true

[base]
enabled = true

[dict]
enabled = true

# path to wordnet data files directory
# https://wordnetcode.princeton.edu/3.0/WNdb-3.0.tar.gz
# directory should have files - data.noun, data.adj, data.adv, data.verb
wordnet_path = "wordnet"

# Maximum results to show per part-of-speech type (noun, verb etc.)
max_results = 5

[dice]
enabled = true

[coin]
enabled = true

[rand]
enabled = true

[epoch]
enabled = true
send_local_time = true

[aerial]
enabled = true

[uuid]
enabled = true
max_results = 25

[sudoku]
enabled = true

[excuse]
enabled = true
file = "data/excuses.txt"
